set type: module
Without this change I got

```
// BaseTestFile.ts
import { test as base } from '@shopware-ag/acceptance-test-suite';
                                                                  
SyntaxError: Cannot use import statement outside a module
```

I am not sure if that is the proper solution, so it's open for discussion